### ISSUE TITLE
Does not handle an array of objects correctly

### ISSUE THREAD

**Issue by mayurm88** [RossWilliams/ts-case-convert#50]
### TypeScript Version

This is tested with TypeScript Version 4.3.5.

### Code

```typescript

import {ObjectToCamel} from "ts-case-convert/lib/caseConvert";

export interface MyObject {
    index: number;
    value?: string
}

export interface MyObjectWithArray {
    object_array?: Array<MyObject>
}

type CaseConvertedObjectWithArray = ObjectToCamel<MyObjectWithArray>;

const request : CaseConvertedObjectWithArray = {
    objectArray: [
        {
            index: 0,
            value: "abc",
        }
    ]
}

request.objectArray?.forEach((value) => {

})
```

### Result

Cannot loop the objectArray as expected. We get the following error while trying to do `forEach`:

`TS2349: This expression is not callable.   Type '{}' has no call signatures.`

Also, the type of `objectArray` becomes `MyObjectWithArray.object_array?: {length: number, toString: {}, toLocaleString: {}, pop: {}, push: {}, concat: {}, join: {}, reverse: {}, shift: {}, slice: {}, sort: {}, ...} | undefined` which shows that `ObjectToCamel` does not play nice with the generic array type `Array<T>`

### Expected Behavior

Should be able to do a `forEach` on the `objectArray`

**Comment by RossWilliams** [comment]
@mayurm88 Thank you for the issue. Test coverage did not include optional arrays. This has been resolved and published as 1.3.1
