### ISSUE TITLE
objectToCamel return type is a Pascal-cased array when the input is a snake-typed array

### ISSUE THREAD

**Issue by filipemir** [RossWilliams/ts-case-convert#52]
I'll submit a broken test via a PR but, for the sake of visibility, here's the issue I'm seeing:

```ts
  type SnakeTyped = { key: string; another_key: string }
  type CamelType = { key: string; anotherKey: string }

  const snakeObject: SnakeTyped[] = [
    { key: 'a', another_key: 'b' },
  ];

  const camelObject: CamelType[] = objectToCamel(snakeObject);
```

The object returned by `objectToCamel` has the keys in camel-case as expected, but the returning type is Pascal-cased. This results in this error:
```
TS2322: Type '{ Key: string; AnotherKey: string; }[]' is not assignable to type 'CamelType[]'.
      Type '{ Key: string; AnotherKey: string; }' is missing the following properties from type 'CamelType': key, anotherKey

           const camelObject: CamelType[] = objectToCamel(snakeObject);
````

**Comment by filipemir** [comment]
Found the offending code and updated the PR https://github.com/RossWilliams/ts-case-convert/pull/53 with the fix. Just an errant `ObjectToPascal` where and `ObjectToCamel` should be.

**Comment by filipemir** [comment]
@RossWilliams any chance we can get this issue resolved by merging the PR?

**Comment by filipemir** [comment]
For anyone who stumbles upon this issue: this package seems to no longer be maintained. I forked it and published it at [typescript-case-convert](https://www.npmjs.com/package/typescript-case-convert)

**Comment by RossWilliams** [comment]
@filipemir I'll get it merged. I've been on holiday.
