### ISSUE TITLE
Converting a Buffer produces an Object rather than a Buffer output

### ISSUE THREAD

**Issue by jtimmons** [RossWilliams/ts-case-convert#58]
Similar to #55. If you have a `Buffer` object as a value in one of your objects it will be converted to an object rather than accepted as a value. This is probably due to the fact that `Buffers` are considered "objects" in JS (ie `typeof Buffer.from('abc') === 'object'`) so the value conversion process is likely catching that.

```ts
const x = objectToCamel({ buffer_key: Buffer.from('abc') });
Buffer.isBuffer(x); // expected: true, actual: false
```

Not sure if you're accepting contributions but would be happy to contribute a fix for this!

**Comment by RossWilliams** [comment]
go for it.

**Comment by hanse** [comment]
Hey. With the new release 2.0.2 including this change you are no longer able to use `ts-case-convert` in an environment where `Buffer` is not defined without poly-filling (most browsers). I think it would be awesome if we could check for the existance of Buffer before using it to avoid having to polyfill 🙂
