### ISSUE TITLE
Crashes when Buffer is not available

### ISSUE THREAD

**Issue by hanse** [RossWilliams/ts-case-convert#60]
Hey.

With the new release 2.0.2 including [this change](https://github.com/RossWilliams/ts-case-convert/issues/58) you are no longer able to use ts-case-convert in an environment where Buffer is not defined without poly-filling (most browsers). I think it would be awesome if the library could check for the existance of `Buffer` before using it to avoid having to polyfill 🙂

**Comment by Aaronius** [comment]
This is still an issue and should not be closed.
