### ISSUE TITLE
ObjectToSnake type doesn't properly work with keys ending on numbers

### ISSUE THREAD

**Issue by uragun91** [RossWilliams/ts-case-convert#64]
**Use case**
I have an object containing `addressLine1` key. 

**Problem**
When I apply ObjectToSnake type to this object, this key is missing in the output. Here is the example:

![](https://i.imgur.com/WQrpIG8.png)

**Comment by guidiego** [comment]
I am having this issue!

**Comment by RossWilliams** [comment]
> I am having this issue!

Thank you. I will implement a fix.
