### ISSUE TITLE
Remove `Buffer` dependency

### ISSUE THREAD

**Issue by alexgorbatchev** [RossWilliams/ts-case-convert#69]
Great package! Unfortunately the global `Buffer` dependency is causing issues when bundling for frontend. It looks like only one method is used, it should be relatively straightforward to replace that dependency with something minimal.

**Comment by noahtigner** [comment]
@alexgorbatchev see [this comment](https://github.com/RossWilliams/ts-case-convert/issues/65#issuecomment-1416482290) for a temporary solution

**Comment by alexgorbatchev** [comment]
I think the right thing to do is to use https://www.npmjs.com/package/is-buffer here for proper comparability

**Comment by alexgorbatchev** [comment]
Not stale

**Comment by tonfido** [comment]
Potential fix: https://github.com/RossWilliams/ts-case-convert/pull/73/
