### ISSUE TITLE
Export types via root export

### ISSUE THREAD

**Issue by dnjstrom** [RossWilliams/ts-case-convert#79]
When using this package I quickly found myself wanting to use the `ObjectToCamel` type (and friends) to type my functions, and while they can be imported as

```import type { ObjectToCamel } from 'ts-case-convert/lib/caseConvert'```

I'd feel more secure relying on them if they were exported as part of the public api, i.e.

```import type { ObjectToCamel } from 'ts-case-convert'```

Are you open to making the types importable like that? If so, I can prepare a PR 👍

**Comment by real2two** [comment]
+1 I'd very much like this as well.
